columns:
  target: "Outcome"
  numerical:
    - "Pregnancies"
    - "Glucose"
    - "BloodPressure"
    - "SkinThickness"
    - "Insulin"
    - "BMI"
    - "DiabetesPedigreeFunction"
    - "Age"
split:
  train: 0.7
  test: 0.15
  validate: 0.15
  random_state: 42
