columns:
  categorical:
    - "Outcome"
  numerical:
    - "Pregnancies"
    - "Glucose"
    - "BloodPressure"
    - "SkinThickness"
    - "Insulin"
    - "BMI"
    - "DiabetesPedigreeFunction"
    - "Age"

split:
  train: 0.7
  test: 0.15
  validate: 0.15
  random_state: 42

models:
  names: ["rf", "lr", "knn", "svc", "dt", "ada", "gbm", "xgb", "lgbm"]
  metrics: ["Accuracy", "Recall", "Precision", "F1", "AUC"]

missing_values:
  zero_columns: [Glucose, BloodPressure, SkinThickness, Insulin, BMI]
  knn_neighbors: 5

outliers:
  q1: 0.05
  q3: 0.95

